package provider

import (
	"context"
	"errors"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &ClusterResource{}
var _ resource.ResourceWithImportState = &ClusterResource{}

// NewClusterResource creates a new ClusterResource.
func NewClusterResource() resource.Resource {
	return &ClusterResource{}
}

// ClusterResource defines the resource implementation.
type ClusterResource struct {
	client *apiClient
}

// ClusterResourceModel describes the resource data model.
type ClusterResourceModel struct {
	ID                      types.String `tfsdk:"id"`
	Name                    types.String `tfsdk:"name"`
	NamespaceID             types.String `tfsdk:"namespace_id"`
	Domain                  types.String `tfsdk:"domain"`
	FQDN                    types.String `tfsdk:"fqdn"`
	AutoDetectIPAddress     types.String `tfsdk:"auto_detect_ip_address"`
	ManualOverrideIPAddress types.String `tfsdk:"manual_override_ip_address"`
	CreatedAt               types.String `tfsdk:"created_at"`
	UpdatedAt               types.String `tfsdk:"updated_at"`
	Flavor                  types.String `tfsdk:"flavor"`
	HasFailingHealthChecks  types.Bool   `tfsdk:"has_failing_health_checks"`
	OnboardingStatus        types.String `tfsdk:"onboarding_status"`
	ClusterToken            types.String `tfsdk:"cluster_token"`
}

// ClusterCreateResponse is the response body from POST .../clusters. It embeds
// the cluster fields and adds the one-time `refreshToken` (the cluster identity
// token, used by the Pomerium proxy to authenticate to the Pomerium Zero API).
type ClusterCreateResponse struct {
	Cluster
	RefreshToken string `json:"refreshToken"`
}

// Metadata sets the resource type name for the ClusterResource.
func (r *ClusterResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_cluster"
}

// Schema defines the structure and attributes of the ClusterResource.
func (r *ClusterResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages a Pomerium Zero Cluster. This resource allows you to create, update, and delete clusters in your Pomerium Zero organization.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "The unique identifier of the cluster. This is automatically generated by Pomerium Zero.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "The name of the cluster. This must be unique within your organization.",
				Required:            true,
			},
			"namespace_id": schema.StringAttribute{
				MarkdownDescription: "The namespace ID of the cluster. This is automatically generated by Pomerium Zero and is used for creating routes and policies.",
				Computed:            true,
			},
			"domain": schema.StringAttribute{
				MarkdownDescription: "The subdomain slug used to generate the cluster's FQDN. The Pomerium Zero API rejects arbitrary user-chosen slugs — only values minted by the API's `generateSubdomainName` endpoint are accepted. The provider mints one transparently at create time, so leave this unset for new clusters. You may pin a previously-minted slug (e.g. for a cluster that was first created elsewhere) by setting it explicitly.",
				Optional:            true,
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"fqdn": schema.StringAttribute{
				MarkdownDescription: "The fully qualified domain name (FQDN) of the cluster. This is automatically generated based on the cluster's domain.",
				Computed:            true,
			},
			"auto_detect_ip_address": schema.StringAttribute{
				MarkdownDescription: "The auto-detected IP address of the cluster. This is determined by Pomerium Zero.",
				Computed:            true,
			},
			"manual_override_ip_address": schema.StringAttribute{
				MarkdownDescription: "Manually-specified IP address for the cluster. If unset, Pomerium Zero uses the auto-detected address.",
				Optional:            true,
			},
			"created_at": schema.StringAttribute{
				MarkdownDescription: "The timestamp when the cluster was created.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"updated_at": schema.StringAttribute{
				MarkdownDescription: "The timestamp when the cluster was last updated.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"flavor": schema.StringAttribute{
				MarkdownDescription: "The cluster flavor: `standard` or `hosted`. Defaults to `standard` if unset.",
				Optional:            true,
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"has_failing_health_checks": schema.BoolAttribute{
				MarkdownDescription: "Whether the cluster currently has failing health checks.",
				Computed:            true,
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.UseStateForUnknown(),
				},
			},
			"onboarding_status": schema.StringAttribute{
				MarkdownDescription: "The onboarding status of the cluster (e.g. `in_progress`, `complete`).",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"cluster_token": schema.StringAttribute{
				MarkdownDescription: "The cluster identity token (refresh token) used by the Pomerium proxy to authenticate to the Pomerium Zero API. Set in the `BOOTSTRAP_SERVICE_ACCOUNT_TOKEN`/`POMERIUM_ZERO_TOKEN` env var on the proxy. The API only emits this value at cluster create time and provides no way to retrieve it later. Resources created by Terraform capture it automatically. Imported clusters have no token in state — the only way to obtain a token for a pre-existing cluster is to recreate it.",
				Computed:            true,
				Sensitive:           true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

// Configure prepares the ClusterResource with provider data.
func (r *ClusterResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*apiClient)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *apiClient, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	r.client = client
}

// Create creates a new cluster in Pomerium Zero.
func (r *ClusterResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan ClusterResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// The API requires `domain` in the create body, but only accepts slugs it
	// has minted via generateSubdomainName. If the user did not pin a slug,
	// mint one transparently.
	if plan.Domain.IsNull() || plan.Domain.IsUnknown() || plan.Domain.ValueString() == "" {
		var minted struct {
			Name string `json:"name"`
		}
		if err := r.client.get(ctx, r.client.generateSubdomainURL(), &minted); err != nil {
			resp.Diagnostics.AddError("Error generating cluster subdomain", err.Error())
			return
		}
		plan.Domain = types.StringValue(minted.Name)
	}

	body := buildClusterRequestBody(&plan)
	body["domain"] = plan.Domain.ValueString()
	var created ClusterCreateResponse
	if err := r.client.post(ctx, r.client.clustersURL(), body, http.StatusCreated, &created); err != nil {
		resp.Diagnostics.AddError("Error creating cluster", err.Error())
		return
	}

	updateClusterResourceModel(&plan, &created.Cluster)
	plan.ClusterToken = types.StringValue(created.RefreshToken)
	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

// Read retrieves information about a Pomerium Zero cluster.
func (r *ClusterResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state ClusterResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var cluster Cluster
	if err := r.client.get(ctx, r.client.clusterURL(state.ID.ValueString()), &cluster); err != nil {
		if errors.Is(err, errNotFound) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading cluster", err.Error())
		return
	}

	prevUpdatedAt := state.UpdatedAt
	prevToken := state.ClusterToken
	updateClusterResourceModel(&state, &cluster)
	// Preserve the state's updated_at on Read — see route_resource.go for rationale.
	state.UpdatedAt = prevUpdatedAt
	// The GET cluster endpoint does not return the cluster token; preserve it from state.
	state.ClusterToken = prevToken
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

// Update updates an existing cluster in Pomerium Zero.
func (r *ClusterResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan ClusterResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var state ClusterResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := buildClusterRequestBody(&plan)
	var cluster Cluster
	if err := r.client.put(ctx, r.client.clusterURL(plan.ID.ValueString()), body, &cluster); err != nil {
		resp.Diagnostics.AddError("Error updating cluster", err.Error())
		return
	}

	updateClusterResourceModel(&plan, &cluster)
	plan.UpdatedAt = state.UpdatedAt
	plan.ClusterToken = state.ClusterToken
	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

// Delete deletes a cluster from Pomerium Zero.
func (r *ClusterResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state ClusterResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if err := r.client.delete(ctx, r.client.clusterURL(state.ID.ValueString())); err != nil {
		resp.Diagnostics.AddError("Error deleting cluster", err.Error())
	}
}

// ImportState imports an existing cluster into Terraform by name.
func (r *ClusterResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	var clusters []Cluster
	if err := r.client.get(ctx, r.client.clustersURL(), &clusters); err != nil {
		resp.Diagnostics.AddError("Error importing cluster", fmt.Sprintf("Could not list clusters: %s", err))
		return
	}

	for _, c := range clusters {
		if c.Name == req.ID {
			var m ClusterResourceModel
			updateClusterResourceModel(&m, &c)
			resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
			resp.Diagnostics.AddWarning(
				"Cluster token not available after import",
				"The Pomerium Zero API only returns the cluster identity token at create time. "+
					"The imported cluster's `cluster_token` is null in state and cannot be retrieved. "+
					"To obtain a token for this cluster you must recreate it (taint + apply, or destroy + apply).",
			)
			return
		}
	}

	resp.Diagnostics.AddError(
		"Error importing cluster",
		fmt.Sprintf("Could not find cluster with name %q", req.ID),
	)
}

// updateClusterResourceModel updates the ClusterResourceModel with data from a Cluster.
func updateClusterResourceModel(model *ClusterResourceModel, cluster *Cluster) {
	model.ID = types.StringValue(cluster.ID)
	model.Name = types.StringValue(cluster.Name)
	model.NamespaceID = types.StringValue(cluster.NamespaceID)
	model.Domain = types.StringValue(cluster.Domain)
	model.FQDN = types.StringValue(cluster.FQDN)
	model.AutoDetectIPAddress = types.StringValue(cluster.AutoDetectIPAddress)
	if cluster.ManualOverrideIPAddress != "" {
		model.ManualOverrideIPAddress = types.StringValue(cluster.ManualOverrideIPAddress)
	} else {
		model.ManualOverrideIPAddress = types.StringNull()
	}
	model.CreatedAt = types.StringValue(cluster.CreatedAt)
	model.UpdatedAt = types.StringValue(cluster.UpdatedAt)
	model.Flavor = types.StringValue(cluster.Flavor)
	model.HasFailingHealthChecks = types.BoolValue(cluster.HasFailingHealthChecks)
	model.OnboardingStatus = types.StringValue(cluster.OnboardingStatus)
}

// buildClusterRequestBody assembles the JSON body for create/update calls,
// containing only the user-settable ClusterProperties fields. Server-assigned
// fields (domain, fqdn, etc.) are excluded — the API rejects requests that
// attempt to set them.
func buildClusterRequestBody(model *ClusterResourceModel) map[string]interface{} {
	body := map[string]interface{}{
		"name": model.Name.ValueString(),
	}
	if !model.Flavor.IsNull() && !model.Flavor.IsUnknown() {
		body["flavor"] = model.Flavor.ValueString()
	}
	if !model.ManualOverrideIPAddress.IsNull() && !model.ManualOverrideIPAddress.IsUnknown() {
		body["manualOverrideIpAddress"] = model.ManualOverrideIPAddress.ValueString()
	}
	return body
}
