package provider

import (
	"context"
	"errors"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &ClusterResource{}
var _ resource.ResourceWithImportState = &ClusterResource{}

// NewClusterResource creates a new ClusterResource.
func NewClusterResource() resource.Resource {
	return &ClusterResource{}
}

// ClusterResource defines the resource implementation.
type ClusterResource struct {
	client *apiClient
}

// ClusterResourceModel describes the resource data model.
type ClusterResourceModel struct {
	ID                  types.String `tfsdk:"id"`
	Name                types.String `tfsdk:"name"`
	NamespaceID         types.String `tfsdk:"namespace_id"`
	Domain              types.String `tfsdk:"domain"`
	FQDN                types.String `tfsdk:"fqdn"`
	AutoDetectIPAddress types.String `tfsdk:"auto_detect_ip_address"`
	CreatedAt           types.String `tfsdk:"created_at"`
	UpdatedAt           types.String `tfsdk:"updated_at"`
}

// Metadata sets the resource type name for the ClusterResource.
func (r *ClusterResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_cluster"
}

// Schema defines the structure and attributes of the ClusterResource.
func (r *ClusterResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages a Pomerium Zero Cluster. This resource allows you to create, update, and delete clusters in your Pomerium Zero organization.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "The unique identifier of the cluster. This is automatically generated by Pomerium Zero.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "The name of the cluster. This must be unique within your organization.",
				Required:            true,
			},
			"namespace_id": schema.StringAttribute{
				MarkdownDescription: "The namespace ID of the cluster. This is automatically generated by Pomerium Zero and is used for creating routes and policies.",
				Computed:            true,
			},
			"domain": schema.StringAttribute{
				MarkdownDescription: "The domain associated with this cluster. This is used to generate the FQDN for the cluster.",
				Required:            true,
			},
			"fqdn": schema.StringAttribute{
				MarkdownDescription: "The fully qualified domain name (FQDN) of the cluster. This is automatically generated based on the cluster's domain.",
				Computed:            true,
			},
			"auto_detect_ip_address": schema.StringAttribute{
				MarkdownDescription: "The auto-detected IP address of the cluster. This is determined by Pomerium Zero.",
				Computed:            true,
			},
			"created_at": schema.StringAttribute{
				MarkdownDescription: "The timestamp when the cluster was created.",
				Computed:            true,
			},
			"updated_at": schema.StringAttribute{
				MarkdownDescription: "The timestamp when the cluster was last updated.",
				Computed:            true,
			},
		},
	}
}

// Configure prepares the ClusterResource with provider data.
func (r *ClusterResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*apiClient)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *apiClient, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	r.client = client
}

// Create creates a new cluster in Pomerium Zero.
func (r *ClusterResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan ClusterResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := map[string]string{
		"name":   plan.Name.ValueString(),
		"domain": plan.Domain.ValueString(),
	}
	var cluster Cluster
	if err := r.client.post(ctx, r.client.clustersURL(), body, http.StatusCreated, &cluster); err != nil {
		resp.Diagnostics.AddError("Error creating cluster", err.Error())
		return
	}

	updateClusterResourceModel(&plan, &cluster)
	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

// Read retrieves information about a Pomerium Zero cluster.
func (r *ClusterResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state ClusterResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var cluster Cluster
	if err := r.client.get(ctx, r.client.clusterURL(state.ID.ValueString()), &cluster); err != nil {
		if errors.Is(err, errNotFound) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading cluster", err.Error())
		return
	}

	updateClusterResourceModel(&state, &cluster)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

// Update updates an existing cluster in Pomerium Zero.
func (r *ClusterResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan ClusterResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := map[string]string{
		"name":   plan.Name.ValueString(),
		"domain": plan.Domain.ValueString(),
	}
	var cluster Cluster
	if err := r.client.put(ctx, r.client.clusterURL(plan.ID.ValueString()), body, &cluster); err != nil {
		resp.Diagnostics.AddError("Error updating cluster", err.Error())
		return
	}

	updateClusterResourceModel(&plan, &cluster)
	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

// Delete deletes a cluster from Pomerium Zero.
func (r *ClusterResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state ClusterResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if err := r.client.delete(ctx, r.client.clusterURL(state.ID.ValueString())); err != nil {
		resp.Diagnostics.AddError("Error deleting cluster", err.Error())
	}
}

// ImportState imports an existing cluster into Terraform by name.
func (r *ClusterResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	var clusters []Cluster
	if err := r.client.get(ctx, r.client.clustersURL(), &clusters); err != nil {
		resp.Diagnostics.AddError("Error importing cluster", fmt.Sprintf("Could not list clusters: %s", err))
		return
	}

	for _, c := range clusters {
		if c.Name == req.ID {
			resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), c.ID)...)
			resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("name"), c.Name)...)
			resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("namespace_id"), c.NamespaceID)...)
			resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("domain"), c.Domain)...)
			resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("fqdn"), c.FQDN)...)
			resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("auto_detect_ip_address"), c.AutoDetectIPAddress)...)
			resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("created_at"), c.CreatedAt)...)
			resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("updated_at"), c.UpdatedAt)...)
			return
		}
	}

	resp.Diagnostics.AddError(
		"Error importing cluster",
		fmt.Sprintf("Could not find cluster with name %q", req.ID),
	)
}

// updateClusterResourceModel updates the ClusterResourceModel with data from a Cluster.
func updateClusterResourceModel(model *ClusterResourceModel, cluster *Cluster) {
	model.ID = types.StringValue(cluster.ID)
	model.Name = types.StringValue(cluster.Name)
	model.NamespaceID = types.StringValue(cluster.NamespaceID)
	model.Domain = types.StringValue(cluster.Domain)
	model.FQDN = types.StringValue(cluster.FQDN)
	model.AutoDetectIPAddress = types.StringValue(cluster.AutoDetectIPAddress)
	model.CreatedAt = types.StringValue(cluster.CreatedAt)
	model.UpdatedAt = types.StringValue(cluster.UpdatedAt)
}
